package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/graphql/introspection"
	"github.com/health-hub-bot-api/internal/domain/analysis"
)

// Type is the resolver for the type field.
func (r *__FieldResolver) Type(ctx context.Context, obj *introspection.Field) (analysis.Type, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Type is the resolver for the type field.
func (r *__InputValueResolver) Type(ctx context.Context, obj *introspection.InputValue) (analysis.Type, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Types is the resolver for the types field.
func (r *__SchemaResolver) Types(ctx context.Context, obj *introspection.Schema) ([]analysis.Type, error) {
	panic(fmt.Errorf("not implemented: Types - types"))
}

// QueryType is the resolver for the queryType field.
func (r *__SchemaResolver) QueryType(ctx context.Context, obj *introspection.Schema) (analysis.Type, error) {
	panic(fmt.Errorf("not implemented: QueryType - queryType"))
}

// MutationType is the resolver for the mutationType field.
func (r *__SchemaResolver) MutationType(ctx context.Context, obj *introspection.Schema) (*analysis.Type, error) {
	panic(fmt.Errorf("not implemented: MutationType - mutationType"))
}

// SubscriptionType is the resolver for the subscriptionType field.
func (r *__SchemaResolver) SubscriptionType(ctx context.Context, obj *introspection.Schema) (*analysis.Type, error) {
	panic(fmt.Errorf("not implemented: SubscriptionType - subscriptionType"))
}

// Kind is the resolver for the kind field.
func (r *__TypeResolver) Kind(ctx context.Context, obj *analysis.Type) (string, error) {
	panic(fmt.Errorf("not implemented: Kind - kind"))
}

// Name is the resolver for the name field.
func (r *__TypeResolver) Name(ctx context.Context, obj *analysis.Type) (*string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Description is the resolver for the description field.
func (r *__TypeResolver) Description(ctx context.Context, obj *analysis.Type) (*string, error) {
	panic(fmt.Errorf("not implemented: Description - description"))
}

// SpecifiedByURL is the resolver for the specifiedByURL field.
func (r *__TypeResolver) SpecifiedByURL(ctx context.Context, obj *analysis.Type) (*string, error) {
	panic(fmt.Errorf("not implemented: SpecifiedByURL - specifiedByURL"))
}

// Fields is the resolver for the fields field.
func (r *__TypeResolver) Fields(ctx context.Context, obj *analysis.Type, includeDeprecated *bool) ([]*introspection.Field, error) {
	panic(fmt.Errorf("not implemented: Fields - fields"))
}

// Interfaces is the resolver for the interfaces field.
func (r *__TypeResolver) Interfaces(ctx context.Context, obj *analysis.Type) ([]analysis.Type, error) {
	panic(fmt.Errorf("not implemented: Interfaces - interfaces"))
}

// PossibleTypes is the resolver for the possibleTypes field.
func (r *__TypeResolver) PossibleTypes(ctx context.Context, obj *analysis.Type) ([]analysis.Type, error) {
	panic(fmt.Errorf("not implemented: PossibleTypes - possibleTypes"))
}

// EnumValues is the resolver for the enumValues field.
func (r *__TypeResolver) EnumValues(ctx context.Context, obj *analysis.Type, includeDeprecated *bool) ([]*introspection.EnumValue, error) {
	panic(fmt.Errorf("not implemented: EnumValues - enumValues"))
}

// InputFields is the resolver for the inputFields field.
func (r *__TypeResolver) InputFields(ctx context.Context, obj *analysis.Type, includeDeprecated *bool) ([]*introspection.InputValue, error) {
	panic(fmt.Errorf("not implemented: InputFields - inputFields"))
}

// OfType is the resolver for the ofType field.
func (r *__TypeResolver) OfType(ctx context.Context, obj *analysis.Type) (*analysis.Type, error) {
	panic(fmt.Errorf("not implemented: OfType - ofType"))
}

// IsOneOf is the resolver for the isOneOf field.
func (r *__TypeResolver) IsOneOf(ctx context.Context, obj *analysis.Type) (*bool, error) {
	panic(fmt.Errorf("not implemented: IsOneOf - isOneOf"))
}

// __Field returns generated.__FieldResolver implementation.
// Используем анонимный интерфейс, так как __FieldResolver не экспортирован из generated
func (r *Resolver) __Field() interface {
	Type(context.Context, *introspection.Field) (analysis.Type, error)
} {
	return &__FieldResolver{r}
}

// __InputValue returns generated.__InputValueResolver implementation.
func (r *Resolver) __InputValue() interface {
	Type(context.Context, *introspection.InputValue) (analysis.Type, error)
} {
	return &__InputValueResolver{r}
}

// __Schema returns generated.__SchemaResolver implementation.
func (r *Resolver) __Schema() interface {
	Types(context.Context, *introspection.Schema) ([]analysis.Type, error)
	QueryType(context.Context, *introspection.Schema) (analysis.Type, error)
	MutationType(context.Context, *introspection.Schema) (*analysis.Type, error)
	SubscriptionType(context.Context, *introspection.Schema) (*analysis.Type, error)
} {
	return &__SchemaResolver{r}
}

// __Type returns generated.__TypeResolver implementation.
func (r *Resolver) __Type() interface {
	Kind(context.Context, *analysis.Type) (string, error)
	Name(context.Context, *analysis.Type) (*string, error)
	Description(context.Context, *analysis.Type) (*string, error)
	SpecifiedByURL(context.Context, *analysis.Type) (*string, error)
	Fields(context.Context, *analysis.Type, *bool) ([]*introspection.Field, error)
	Interfaces(context.Context, *analysis.Type) ([]analysis.Type, error)
	PossibleTypes(context.Context, *analysis.Type) ([]analysis.Type, error)
	EnumValues(context.Context, *analysis.Type, *bool) ([]*introspection.EnumValue, error)
	InputFields(context.Context, *analysis.Type, *bool) ([]*introspection.InputValue, error)
	OfType(context.Context, *analysis.Type) (*analysis.Type, error)
	IsOneOf(context.Context, *analysis.Type) (*bool, error)
} {
	return &__TypeResolver{r}
}

type __FieldResolver struct{ *Resolver }
type __InputValueResolver struct{ *Resolver }
type __SchemaResolver struct{ *Resolver }
type __TypeResolver struct{ *Resolver }
