package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"time"

	"github.com/health-hub-bot-api/graphql/generated"
	"github.com/health-hub-bot-api/internal/domain/analysis"
	"github.com/health-hub-bot-api/internal/domain/doctorvisit"
	"github.com/health-hub-bot-api/internal/domain/medication"
	"github.com/health-hub-bot-api/internal/domain/symptom"
	"github.com/health-hub-bot-api/internal/domain/user"
)

// ID is the resolver for the id field.
func (r *analysisResolver) ID(ctx context.Context, obj *analysis.Analysis) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *analysisResolver) UserID(ctx context.Context, obj *analysis.Analysis) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// Type is the resolver for the type field.
func (r *analysisResolver) Type(ctx context.Context, obj *analysis.Analysis) (generated.AnalysisType, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// ID is the resolver for the id field.
func (r *doctorVisitResolver) ID(ctx context.Context, obj *doctorvisit.DoctorVisit) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *doctorVisitResolver) UserID(ctx context.Context, obj *doctorvisit.DoctorVisit) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ReportData is the resolver for the reportData field.
func (r *doctorVisitResolver) ReportData(ctx context.Context, obj *doctorvisit.DoctorVisit) (*string, error) {
	panic(fmt.Errorf("not implemented: ReportData - reportData"))
}

// ID is the resolver for the id field.
func (r *medicationResolver) ID(ctx context.Context, obj *medication.Medication) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *medicationResolver) UserID(ctx context.Context, obj *medication.Medication) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ID is the resolver for the id field.
func (r *medicationIntakeResolver) ID(ctx context.Context, obj *medication.MedicationIntake) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// MedicationID is the resolver for the medicationId field.
func (r *medicationIntakeResolver) MedicationID(ctx context.Context, obj *medication.MedicationIntake) (string, error) {
	panic(fmt.Errorf("not implemented: MedicationID - medicationId"))
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, input generated.UpdateUserProfileInput) (*user.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUserProfile - updateUserProfile"))
}

// CreateSymptomEntry is the resolver for the createSymptomEntry field.
func (r *mutationResolver) CreateSymptomEntry(ctx context.Context, input generated.CreateSymptomEntryInput) (*symptom.SymptomEntry, error) {
	panic(fmt.Errorf("not implemented: CreateSymptomEntry - createSymptomEntry"))
}

// UpdateSymptomEntry is the resolver for the updateSymptomEntry field.
func (r *mutationResolver) UpdateSymptomEntry(ctx context.Context, id string, input generated.UpdateSymptomEntryInput) (*symptom.SymptomEntry, error) {
	panic(fmt.Errorf("not implemented: UpdateSymptomEntry - updateSymptomEntry"))
}

// DeleteSymptomEntry is the resolver for the deleteSymptomEntry field.
func (r *mutationResolver) DeleteSymptomEntry(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSymptomEntry - deleteSymptomEntry"))
}

// CreateAnalysis is the resolver for the createAnalysis field.
func (r *mutationResolver) CreateAnalysis(ctx context.Context, input generated.CreateAnalysisInput) (*analysis.Analysis, error) {
	panic(fmt.Errorf("not implemented: CreateAnalysis - createAnalysis"))
}

// UpdateAnalysis is the resolver for the updateAnalysis field.
func (r *mutationResolver) UpdateAnalysis(ctx context.Context, id string, input generated.UpdateAnalysisInput) (*analysis.Analysis, error) {
	panic(fmt.Errorf("not implemented: UpdateAnalysis - updateAnalysis"))
}

// DeleteAnalysis is the resolver for the deleteAnalysis field.
func (r *mutationResolver) DeleteAnalysis(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteAnalysis - deleteAnalysis"))
}

// CreateMedication is the resolver for the createMedication field.
func (r *mutationResolver) CreateMedication(ctx context.Context, input generated.CreateMedicationInput) (*medication.Medication, error) {
	panic(fmt.Errorf("not implemented: CreateMedication - createMedication"))
}

// UpdateMedication is the resolver for the updateMedication field.
func (r *mutationResolver) UpdateMedication(ctx context.Context, id string, input generated.UpdateMedicationInput) (*medication.Medication, error) {
	panic(fmt.Errorf("not implemented: UpdateMedication - updateMedication"))
}

// DeleteMedication is the resolver for the deleteMedication field.
func (r *mutationResolver) DeleteMedication(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteMedication - deleteMedication"))
}

// MarkMedicationIntake is the resolver for the markMedicationIntake field.
func (r *mutationResolver) MarkMedicationIntake(ctx context.Context, input generated.MarkMedicationIntakeInput) (*medication.MedicationIntake, error) {
	panic(fmt.Errorf("not implemented: MarkMedicationIntake - markMedicationIntake"))
}

// CreateDoctorVisit is the resolver for the createDoctorVisit field.
func (r *mutationResolver) CreateDoctorVisit(ctx context.Context, input generated.CreateDoctorVisitInput) (*doctorvisit.DoctorVisit, error) {
	panic(fmt.Errorf("not implemented: CreateDoctorVisit - createDoctorVisit"))
}

// UpdateDoctorVisit is the resolver for the updateDoctorVisit field.
func (r *mutationResolver) UpdateDoctorVisit(ctx context.Context, id string, input generated.UpdateDoctorVisitInput) (*doctorvisit.DoctorVisit, error) {
	panic(fmt.Errorf("not implemented: UpdateDoctorVisit - updateDoctorVisit"))
}

// DeleteDoctorVisit is the resolver for the deleteDoctorVisit field.
func (r *mutationResolver) DeleteDoctorVisit(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteDoctorVisit - deleteDoctorVisit"))
}

// GenerateDoctorVisitReport is the resolver for the generateDoctorVisitReport field.
func (r *mutationResolver) GenerateDoctorVisitReport(ctx context.Context, visitID string, startDate *time.Time, endDate *time.Time) (*generated.DoctorVisitReport, error) {
	panic(fmt.Errorf("not implemented: GenerateDoctorVisitReport - generateDoctorVisitReport"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*user.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Symptoms is the resolver for the symptoms field.
func (r *queryResolver) Symptoms(ctx context.Context, filter *generated.SymptomFilter, limit *int, offset *int) (*generated.SymptomConnection, error) {
	panic(fmt.Errorf("not implemented: Symptoms - symptoms"))
}

// Symptom is the resolver for the symptom field.
func (r *queryResolver) Symptom(ctx context.Context, id string) (*symptom.SymptomEntry, error) {
	panic(fmt.Errorf("not implemented: Symptom - symptom"))
}

// Analyses is the resolver for the analyses field.
func (r *queryResolver) Analyses(ctx context.Context, filter *generated.AnalysisFilter, limit *int, offset *int) (*generated.AnalysisConnection, error) {
	panic(fmt.Errorf("not implemented: Analyses - analyses"))
}

// Analysis is the resolver for the analysis field.
func (r *queryResolver) Analysis(ctx context.Context, id string) (*analysis.Analysis, error) {
	panic(fmt.Errorf("not implemented: Analysis - analysis"))
}

// Medications is the resolver for the medications field.
func (r *queryResolver) Medications(ctx context.Context, activeOnly *bool) ([]*medication.Medication, error) {
	panic(fmt.Errorf("not implemented: Medications - medications"))
}

// Medication is the resolver for the medication field.
func (r *queryResolver) Medication(ctx context.Context, id string) (*medication.Medication, error) {
	panic(fmt.Errorf("not implemented: Medication - medication"))
}

// MedicationIntakes is the resolver for the medicationIntakes field.
func (r *queryResolver) MedicationIntakes(ctx context.Context, medicationID string, date *time.Time) ([]*medication.MedicationIntake, error) {
	panic(fmt.Errorf("not implemented: MedicationIntakes - medicationIntakes"))
}

// DoctorVisits is the resolver for the doctorVisits field.
func (r *queryResolver) DoctorVisits(ctx context.Context, limit *int, offset *int) (*generated.DoctorVisitConnection, error) {
	panic(fmt.Errorf("not implemented: DoctorVisits - doctorVisits"))
}

// DoctorVisit is the resolver for the doctorVisit field.
func (r *queryResolver) DoctorVisit(ctx context.Context, id string) (*doctorvisit.DoctorVisit, error) {
	panic(fmt.Errorf("not implemented: DoctorVisit - doctorVisit"))
}

// DoctorVisitReport is the resolver for the doctorVisitReport field.
func (r *queryResolver) DoctorVisitReport(ctx context.Context, visitID string, startDate *time.Time, endDate *time.Time) (*generated.DoctorVisitReport, error) {
	panic(fmt.Errorf("not implemented: DoctorVisitReport - doctorVisitReport"))
}

// ID is the resolver for the id field.
func (r *symptomEntryResolver) ID(ctx context.Context, obj *symptom.SymptomEntry) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// UserID is the resolver for the userId field.
func (r *symptomEntryResolver) UserID(ctx context.Context, obj *symptom.SymptomEntry) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *user.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// TelegramUserID is the resolver for the telegramUserId field.
func (r *userResolver) TelegramUserID(ctx context.Context, obj *user.User) (string, error) {
	panic(fmt.Errorf("not implemented: TelegramUserID - telegramUserId"))
}

// DataPoints is the resolver for the dataPoints field.
func (r *wellbeingTrendResolver) DataPoints(ctx context.Context, obj *doctorvisit.WellbeingTrend) ([]*symptom.WellbeingDataPoint, error) {
	panic(fmt.Errorf("not implemented: DataPoints - dataPoints"))
}

// Analysis returns generated.AnalysisResolver implementation.
func (r *Resolver) Analysis() generated.AnalysisResolver { return &analysisResolver{r} }

// DoctorVisit returns generated.DoctorVisitResolver implementation.
func (r *Resolver) DoctorVisit() generated.DoctorVisitResolver { return &doctorVisitResolver{r} }

// Medication returns generated.MedicationResolver implementation.
func (r *Resolver) Medication() generated.MedicationResolver { return &medicationResolver{r} }

// MedicationIntake returns generated.MedicationIntakeResolver implementation.
func (r *Resolver) MedicationIntake() generated.MedicationIntakeResolver {
	return &medicationIntakeResolver{r}
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// SymptomEntry returns generated.SymptomEntryResolver implementation.
func (r *Resolver) SymptomEntry() generated.SymptomEntryResolver { return &symptomEntryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

// WellbeingTrend returns generated.WellbeingTrendResolver implementation.
func (r *Resolver) WellbeingTrend() generated.WellbeingTrendResolver {
	return &wellbeingTrendResolver{r}
}

type analysisResolver struct{ *Resolver }
type doctorVisitResolver struct{ *Resolver }
type medicationResolver struct{ *Resolver }
type medicationIntakeResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type symptomEntryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type wellbeingTrendResolver struct{ *Resolver }
